spring:
  datasource:
    username: usefulplants
    password: usefulplants
    url: jdbc:mysql://localhost:3306/usefulplants
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
         
  sql:
    init:
      mode: never 
      

  servlet:
    multipart:
      max-file-size: 10MB
      
      
springdoc:
  swagger-ui:
    path: /

    
